"""empty message

Revision ID: 1df46d62f17a
Revises: c23a4e05ee15
Create Date: 2022-10-23 18:19:49.953566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df46d62f17a'
down_revision = 'c23a4e05ee15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
