"""empty message

Revision ID: 2879a1eb161e
Revises: 5b41466ae76b
Create Date: 2022-10-23 18:32:45.189884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2879a1eb161e'
down_revision = '5b41466ae76b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
