"""empty message

Revision ID: 5b41466ae76b
Revises: 1df46d62f17a
Create Date: 2022-10-23 18:27:13.648502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b41466ae76b'
down_revision = '1df46d62f17a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
