"""empty message

Revision ID: 77507aed3ba5
Revises: 2879a1eb161e
Create Date: 2022-10-23 18:35:00.954992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77507aed3ba5'
down_revision = '2879a1eb161e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
