"""empty message

Revision ID: 98c4df3454a4
Revises: 5c973d855d26
Create Date: 2022-10-23 15:37:17.854851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c4df3454a4'
down_revision = '5c973d855d26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
