"""empty message

Revision ID: c23a4e05ee15
Revises: 3dcf0bae0ce6
Create Date: 2022-10-23 18:15:42.224391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23a4e05ee15'
down_revision = '3dcf0bae0ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
